#!/bin/bash

echo "Backing up Cyber Security Documents" 

rclone bisync /home/tom/Documents/BSc\ Cyber\ Security Drive:BSc\ Cyber\ Security -P --exclude "node_modules/**" --copy-links


echo "Backung up obsidian"

rclone sync /obsidian Drive:Backups/Obsidian -P --copy-links --exclude ".git/"
