#!/bin/bash
## Description: change brightness
## Dependencies: cat, echo, sudo, tee
## Usage: brightness [-set,-get,-inc,-dec] [value]
## Arguments: -set [value], -get, -inc [value], -dec [value]
## Author: Tom Steer


MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CURRENT_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
VALUE=$2


# Set brightness
if [ "$1" = "-set" ]; then
	if [ "$2" -gt "$MAX_BRIGHTNESS" ]; then
		VALUE=$MAX_BRIGHTNESS
	fi
	if [ "$2" -lt 0 ]; then
		VALUE=10
	fi
	echo "$VALUE" | sudo tee /sys/class/backlight/intel_backlight/brightness

# Get brightness
elif [ "$1" = "-get" ]; then
	echo "$CURRENT_BRIGHTNESS" 2>&1

# Increase brightness
elif [ "$1" = "-inc" ]; then
	VALUE=$(($CURRENT_BRIGHTNESS + $2))
	if [ "$VALUE" -gt "$MAX_BRIGHTNESS" ]; then
		VALUE=$MAX_BRIGHTNESS
	fi
	if [ "$VALUE" -lt 1 ]; then
		VALUE=10
	fi
	echo "$VALUE" | sudo tee /sys/class/backlight/intel_backlight/brightness
# Decrease brightness
elif [ "$1" = "-dec" ]; then
	VALUE=$(($CURRENT_BRIGHTNESS - $2))
	if [ "$VALUE" -gt "$MAX_BRIGHTNESS" ]; then
		VALUE=$MAX_BRIGHTNESS
	fi
	if [ "$VALUE" -lt 1 ]; then
		VALUE=10
	fi
	echo "$VALUE" | sudo tee /sys/class/backlight/intel_backlight/brightness
fi
