#!/bin/bash
## This script assumes a base arch xorg install
sudo pacman -Syu --noconfirm
sudo pacman -S git --noconfirm --needed
git clone https://github.com/tomsteer1/dotfiles $HOME/dotfiles
git clone https://github.com/tomsteer1/scripts $HOME/scripts
cd $HOME/dotfiles
./install.sh
mkdir $HOME/.ssh
sudo chsh -s /bin/zsh $USER
if [ $(hostname) = "virtual" ]; then
	sudo pacman -S spice-vdagent --noconfirm
	cp $HOME/dotfiles/desktop/virtualxinitrc $HOME/.xinitrc
else
	sudo systemctl enable --now lightdm
fi
