#!/bin/bash
## This script assumes a base arch xorg install
sudo pacman -S git --noconfirm
git clone https://github.com/tomsteer1/dotfiles $HOME/dotfiles
git clone https://github.com/tomsteer1/scripts $HOME/scripts
cd $HOME/dotfiles
./install.sh
mkdir $HOME/.ssh
sudo chsh -s /bin/zsh tom
sudo systemctl enable lightdm
sudo systemctl start lightdm
