#!/bin/bash

dirs=("WM241 - Human Behavior in Cyber Systems" "WM245 - Programming Languages for Cyber Security" "WM242 - Implementing Secure Systems Seminar" "WM243 - Information Management" "WM279 - Information Risk and Security Management" "WM240 - Cyber Context of Software Engineering")

baseDIR="/obsidian/BSc Cyber Security"

for dir in "${dirs[@]}"
do
		mkdir -p "$baseDIR/$dir"
done
