#!/bin/zsh
## To use
# source lecture
# lecture

lecture () {
	local modules=("HBCS" "PLCS" "ISS" "IM" "IRSM" "CCSE")
	local rootdir="$HOME/Documents/BSc Cyber Security"
	local dirs=("WM241 - Human Behavior in Cyber Systems" "WM245 - Programming Languages for Cyber Security" "WM242 - Implementing Secure Systems" "WM243 - Information Management" "WM279 - Information Risk and Security Management" "WM240 - Cyber Context of Software Engineering")
	# Create a menu of modules
	for i in {1.."${#modules[@]}"}; do
		echo "$i) ${modules[$i]}"
	done
	read -k1 module
	cd $rootdir/${dirs[$module]}

}

