#!/bin/bash

INVENV=$(python -c 'import sys; print ("1" if hasattr(sys, "real_prefix") else "0")')

if [ $INVENV == "1" ]; then
	nvim "$@"
else
	if [ ! -d /opt/venvs/neovim ]; then
		echo "Neovim virtual environment not found. Please create it first at /opt/venvs/neovim."
		exit 1
	fi

	source /opt/venvs/neovim/bin/activate
	nvim "$@"
fi
